apiVersion: contrail.juniper.net/v1alpha1
kind: Manager
metadata:
  name: cluster1
  namespace: contrail
spec:
  commonConfiguration:
    hostNetwork: true
    nodeSelector:
      node-role.kubernetes.io/master: ""
    keystoneSecretInstance : cluster1-admin-password
  services:
    cassandras:
    - metadata:
        labels:
          contrail_cluster: cluster1
        name: cassandra1
      spec:
        serviceConfiguration:
          containers:
            - name: cassandra
              image: cassandra:3.11.4
            - name: init
              image: python:3.8.2-alpine
            - name: init2
              image: cassandra:3.11.4
    config:
      metadata:
        labels:
          contrail_cluster: cluster1
        name: config1
      spec:
        serviceConfiguration:
          cassandraInstance: cassandra1
          analyticsDataTTL: 2
          analyticsConfigAuditTTL: 2160
          analyticsFlowTTL: 1
          analyticsStatisticsTTL: 2
          containers:
            - name: analyticsapi
              image: tungstenfabric/contrail-analytics-api:latest
            - name: api
              image: tungstenfabric/contrail-controller-config-api:latest
            - name: collector
              image: tungstenfabric/contrail-analytics-collector:latest
            - name: devicemanager
              image: tungstenfabric/contrail-controller-config-devicemgr:latest
              command:
                - "/bin/sh"
                - "-c"
                - "tail -f /dev/null"
            - name: dnsmasq
              image: tungstenfabric/contrail-controller-config-dnsmasq:latest
              command:
                - "/bin/sh"
                - "-c"
                - "tail -f /dev/null"
            - name: init
              image: python:3.8.2-alpine
            - name: init2
              image: busybox:latest
            - name: redis
              image: redis:4.0.2
            - name: schematransformer
              image: tungstenfabric/contrail-controller-config-schema:latest
            - name: servicemonitor
              image: tungstenfabric/contrail-controller-config-svcmonitor:latest
            - name: queryengine
              image: tungstenfabric/contrail-analytics-query-engine:latest
            - name: statusmonitor
              image: steigenhaus/contrail-statusmonitor:latest
          logLevel: SYS_DEBUG
          zookeeperInstance: zookeeper1
    controls:
    - metadata:
        labels:
          contrail_cluster: cluster1
          control_role: master
        name: control1
      spec:
        serviceConfiguration:
          cassandraInstance: cassandra1
          containers:
            - name: control
              image: tungstenfabric/contrail-controller-control-control:latest
            - name: dns
              image: tungstenfabric/contrail-controller-control-dns:latest
            - name: init
              image: python:3.8.2-alpine
            - name: named
              image: tungstenfabric/contrail-controller-control-named:latest
            - name: statusmonitor
              image: steigenhaus/contrail-statusmonitor:latest
          zookeeperInstance: zookeeper1
    provisionManager:
      metadata:
        labels:
          contrail_cluster: cluster1
        name: provmanager1
      spec:
        commonConfiguration:
          replicas: 1
        serviceConfiguration:
          containers:
          - name: init
            image: python:3.8.2-alpine
          - name: provisioner
            image: steigenhaus/contrail-operator-provisioner:latest
    rabbitmq:
      metadata:
        labels:
          contrail_cluster: cluster1
        name: rabbitmq1
      spec:
        serviceConfiguration:
          containers:
          - name: init
            image: python:3.8.2-alpine
          - name: rabbitmq
            image: rabbitmq:3.7
    webui:
      metadata:
        labels:
          contrail_cluster: cluster1
        name: webui1
      spec:
        serviceConfiguration:
          cassandraInstance: cassandra1
          containers:
            - name: init
              image: python:3.8.2-alpine
            - name: redis
              image: redis:4.0.2
            - name: webuijob
              image: tungstenfabric/contrail-controller-webui-job:latest
            - name: webuiweb
              image: tungstenfabric/contrail-controller-webui-web:latest
    zookeepers:
    - metadata:
        labels:
          contrail_cluster: cluster1
        name: zookeeper1
      spec:
        commonConfiguration:
          tolerations:
            - effect: NoSchedule
              operator: Exists
            - effect: NoExecute
              operator: Exists
        serviceConfiguration:
          containers:
            - name: init
              image: python:3.8.2-alpine
            - name: conf-init
              image: python:3.8.2-alpine
            - name: zookeeper
              image: zookeeper:3.5.5
    kubemanagers:
    - metadata:
        labels:
          contrail_cluster: cluster1
        name: kubemanager1
      spec:
        serviceConfiguration:
          cassandraInstance: cassandra1
          zookeeperInstance: zookeeper1
          containers:
            - name: init
              image: python:3.8.2-alpine
            - name: kubemanager
              image: tungstenfabric/contrail-kubernetes-kube-manager:latest
            - name: statusmonitor
              image: steigenhaus/contrail-statusmonitor:latest
          ipFabricForwarding: false
          ipFabricSnat: true
          kubernetesTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
          hostNetworkService: true
          kubernetesClusterName: "test1"
          podSubnets: "10.128.0.0/14"
          serviceSubnets: "172.30.0.0/16"
          kubernetesAPIServer: "api.test1.openshift.hobgoblin.org"
          kubernetesAPISSLPort: 6443
          useKubeadmConfig: false
    vrouters:
    - metadata:
        labels:
          contrail_cluster: cluster1
        name: vroutermasternodes
      spec:
        commonConfiguration:
          nodeSelector:
            node-role.kubernetes.io/master: ""
        serviceConfiguration:
          controlInstance: control1
          contrailStatusImage: tungstenfabric/contrail-status:latest
          containers:
            - name: init
              image: python:3.8.2-alpine
            - name: nodeinit
              image: tungstenfabric/contrail-node-init:latest
            - name: vrouteragent
              image: tungstenfabric/contrail-vrouter-agent:latest
            - name: vroutercni
              image: tungstenfabric/contrail-kubernetes-cni-init:latest
            - name: vrouterkernelbuildinit
              image: tungstenfabric/contrail-vrouter-kernel-build-init:latest
            - name: vrouterkernelinit
              image: steigenhaus/contrail-vrouter-kernel-init:ubi
            - name: multusconfig
              image: busybox:1.31
    - metadata:
        labels:
          contrail_cluster: cluster1
        name: vrouterworkernodes
      spec:
        commonConfiguration:
          nodeSelector:
            node-role.kubernetes.io/worker: ""
        serviceConfiguration:
          controlInstance: control1
          contrailStatusImage: tungstenfabric/contrail-status:latest
          containers:
            - name: init
              image: python:3.8.2-alpine
            - name: nodeinit
              image: tungstenfabric/contrail-node-init:latest
            - name: vrouteragent
              image: tungstenfabric/contrail-vrouter-agent:latest
            - name: vroutercni
              image: tungstenfabric/contrail-kubernetes-cni-init:latest
            - name: vrouterkernelbuildinit
              image: tungstenfabric/contrail-vrouter-kernel-build-init:latest
            - name: vrouterkernelinit
              image: steigenhaus/contrail-vrouter-kernel-init:ubi
            - name: multusconfig
              image: busybox:1.31
    contrailCNIs:
    - metadata:
        labels:
          contrail_cluster: cluster1
        name: cnimasternodes
      spec:
        commonConfiguration:
          nodeSelector:
            node-role.kubernetes.io/master: ""
        serviceConfiguration:
          controlInstance: control1
          kubernetesClusterName: "test1"
          useKubeadmConfig: false
          binariesDirectory: "/var/lib/cni/bin"
          containers:
            - name: vroutercni
              image: tungstenfabric/contrail-kubernetes-cni-init:latest
              command:
              - "sh"
              - "-c"
              - |
                mkdir -p /host/etc_cni/net.d &&
                mkdir -p /var/lib/contrail/ports/vm &&
                cp -f /usr/bin/contrail-k8s-cni /host/opt_cni_bin &&
                chmod 0755 /host/opt_cni_bin/contrail-k8s-cni &&
                cp -f /etc/contrailconfigmaps/10-contrail.conf /host/etc_cni/net.d/10-contrail.conf &&
                tar -C /host/opt_cni_bin -xzf /opt/cni-v0.3.0.tgz &&
                mkdir -p /etc/kubernetes/cni/net.d &&
                cp -f /etc/contrailconfigmaps/10-contrail.conf /etc/kubernetes/cni/net.d/10-contrail.conf &&
                mkdir -p /var/run/multus/cni/net.d &&
                cp -f /etc/contrailconfigmaps/10-contrail.conf /var/run/multus/cni/net.d/80-openshift-network.conf
            - name: multusconfig
              image: busybox:1.31
    - metadata:
        labels:
          contrail_cluster: cluster1
        name: cniworkernodes
      spec:
        commonConfiguration:
          nodeSelector:
            node-role.kubernetes.io/worker: ""
        serviceConfiguration:
          kubernetesClusterName: "test1"
          useKubeadmConfig: false
          binariesDirectory: "/var/lib/cni/bin"
          controlInstance: control1
          containers:
            - name: vroutercni
              image: tungstenfabric/contrail-kubernetes-cni-init:latest
              command:
              - "sh"
              - "-c"
              - |
                mkdir -p /host/etc_cni/net.d &&
                mkdir -p /var/lib/contrail/ports/vm &&
                cp -f /usr/bin/contrail-k8s-cni /host/opt_cni_bin &&
                chmod 0755 /host/opt_cni_bin/contrail-k8s-cni &&
                cp -f /etc/contrailconfigmaps/10-contrail.conf /host/etc_cni/net.d/10-contrail.conf &&
                tar -C /host/opt_cni_bin -xzf /opt/cni-v0.3.0.tgz &&
                mkdir -p /etc/kubernetes/cni/net.d &&
                cp -f /etc/contrailconfigmaps/10-contrail.conf /etc/kubernetes/cni/net.d/10-contrail.conf &&
                mkdir -p /var/run/multus/cni/net.d &&
                cp -f /etc/contrailconfigmaps/10-contrail.conf /var/run/multus/cni/net.d/80-openshift-network.conf
            - name: multusconfig
              image: busybox:1.31
    contrailmonitor:
      metadata:
        labels:
          contrail_cluster: cluster1
        name: contrailmonitor
      spec:
        serviceConfiguration:
          cassandraInstance: cassandra1
          rabbitmqInstance: rabbitmq1
          zookeeperInstance: zookeeper1
          webuiInstance: webui1
          configInstance: config1
          controlInstance: control1
          provisionmanagerInstance: provmanager1

